- name: Add Logstash repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

- name: Enable Elasticsearch repository
  template: src=elasticsearch_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch from repository
  yum: name={{ item }} state=latest
  with_items:
   - elasticsearch

- name: Copy Elasticsearch config file from template
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml

- name: Install plugin HEAD
  command: chdir=/usr/share/elasticsearch/bin ./plugin -install mobz/elasticsearch-head
  notify:
   - restart elasticsearch

- name: Enable elasticsearch service
  service: name=elasticsearch enabled=yes
