export TERM="xterm-256color"

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="pygmalion"
DISABLE_AUTO_UPDATE="true"
plugins=(git git-flow python supervisor)
source $ZSH/oh-my-zsh.sh
unsetopt correct_all
unsetopt correctall
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export VCS=git

# Virtualenv
if [[ -f /usr/share/virtualenvwrapper/virtualenvwrapper.sh ]]; then
    export WORKON_HOME=$HOME/.virtualenvs
    export VIRTUALENVWRAPPER_PYTHON=`which python`
    export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
    source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fi