# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

nodes = [
  { :hostname => 'cloudera', :ip => "192.168.33.100", :run_list => "role[server]"  },
  { :hostname => 'node1', :ip => "192.168.33.101", :run_list =>  "role[node]"  },
  { :hostname => 'node2', :ip => "192.168.33.102", :run_list => "role[node]"  },
  { :hostname => 'node3', :ip => "192.168.33.103", :run_list =>  "role[node]"  }
  ]
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

 
  config.omnibus.chef_version = :latest
  config.vm.box = "centos"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20131103.box"
  config.berkshelf.enabled = true 
  
   
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
 
    node_config.vm.hostname = "#{node[:hostname]}"
    node_config.vm.network :private_network, ip: node[:ip]

  
 
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  
  #if node[:hostname] == nodes.last[:hostname]
    node_config.vm.provision :chef_zero do |chef|
      chef.cookbooks_path = "/opt/chef_cloudera"
      chef.roles_path = "/opt/chef_cloudera/cloudera_server/roles"
       chef.json = {
         mysql: {
          server_root_password: 'rootpass',
          server_debian_password: 'debpass',
          server_repl_password: 'replpass'
        }
      }
    chef.run_list = "#{node[:run_list]}"
#    end
  end
 end
end
end
